sudo: required
services:
  - docker
before_install:
  - docker build -t codingpop/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run codingpop/react-test npm test -- --coverage
after_success:
  - docker build -t codingpop/multi-nginx ./nginx
  - docker build -t codingpop/multi-client ./client
  - docker build -t codingpop/multi-server ./server
  - docker build -t codingpop/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push codingpop/multi-nginx
  - docker push codingpop/multi-client
  - docker push codingpop/multi-server
  - docker push codingpop/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-055770869271
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
